name: notify pr review

on:
  pull_request:
    types: [ reopened ]

jobs:
  notify:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Print event context
        run: echo "${{ toJson(github.event) }}"
      - name: Notify PR Review
        uses: naver/notify-pr-review@v1.2.0
        with:
          token: ${{ secrets.TEST_GITHUB_TOKEN }}
          slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
