name: Request PR Review

on:
  schedule:
    - cron: '0 1 * * 1-5' # 평일 오전 10시마다 수행
  workflow_dispatch:  

jobs:
  send_pr_review_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Review Request to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"channel":"#테스트", "text":"PR Review 요청!"}' \
          'https://slack.com/api/chat.postMessage' \
          -H 'Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}'
